
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Analyzes a user's style DNA based on wardrobe, shoe collection, calendar events, and weather.
 *
 * - analyzeStyleDNA - A function that initiates the style DNA analysis process.
 * - AnalyzeStyleDNAInput - The input type for the analyzeStyleDNA function.
 * - AnalyzeStyleDNAOutput - The return type for the analyzeStyleDNA function.
 * - GoogleCalendarEventSchema - Type for Google Calendar event data.
 * - AccuWeatherSchema - Type for AccuWeather data.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Define schemas for the AccuWeather and Google Calendar APIs (mocked here)
const AccuWeatherSchemaInternal = z.object({
  temperature: z.number().describe('The current temperature in Celsius.'),
  condition: z.string().describe('The current weather condition (e.g., sunny, rainy).'),
});
export type AccuWeatherSchema = z.infer<typeof AccuWeatherSchemaInternal>;


const GoogleCalendarEventSchemaInternal = z.object({
  eventName: z.string().describe('The name of the event.'),
  eventStartDateTime: z.string().describe('The start date and time of the event (ISO format).'),
  eventEndDateTime: z.string().describe('The end date and time of the event (ISO format).'),
  eventType: z.string().describe('The type of event (e.g., business, social).'),
  eventLocation: z.string().optional().describe('The location of the event.'),
});
export type GoogleCalendarEventSchema = z.infer<typeof GoogleCalendarEventSchemaInternal>;


const AnalyzeStyleDNAInputSchema = z.object({
  wardrobeData: z.string().describe('RFID/NFC data representing the user\'s wardrobe collection. These users are fashion-forward and appreciate high-quality, stylish items, often from well-known designers or high-end brands. Their wardrobe reflects a sophisticated taste and a keen eye for current trends as well as timeless pieces. Example: "Item_1_Burberry_TrenchCoat_Beige_SizeM, Item_2_Gucci_SilkBlouse_Cream_SizeS"'),
  shoeCollectionData: z.string().describe('RFID/NFC data representing the user\'s shoe collection. Shoes are a statement for these users, ranging from designer heels and boots to exclusive trainers and elegant flats. Collection emphasizes style, craftsmanship, and brand prestige. Example: "Shoe_1_Chanel_Slingbacks_BeigeBlack_Size39, Shoe_2_ManoloBlahnik_HangisiPumps_BlueSatin_Size39"'),
  accuWeatherInfo: AccuWeatherSchemaInternal.describe('Data from the AccuWeather API.'),
  googleCalendarEvents: z.array(GoogleCalendarEventSchemaInternal).describe('Events from the user\'s Google Calendar.'),
});

export type AnalyzeStyleDNAInput = z.infer<typeof AnalyzeStyleDNAInputSchema>;

const AnalyzeStyleDNAOutputSchema = z.object({
  styleDNA: z.string().describe('CRITICAL: This field MUST contain a single, plain text summary paragraph (approximately 3-4 lines) describing the user\'s style DNA. It should use British English and contemporary fashion language. It MUST NOT be a JSON object. It MUST NOT be a string representation of a JSON object. It MUST NOT echo or replicate the input JSON structure. It must be ONLY the descriptive paragraph text itself.'),
});

export type AnalyzeStyleDNAOutput = z.infer<typeof AnalyzeStyleDNAOutputSchema>;

export async function analyzeStyleDNA(input: AnalyzeStyleDNAInput): Promise<AnalyzeStyleDNAOutput> {
  return analyzeStyleDNAFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeStyleDNAPrompt',
  input: {schema: AnalyzeStyleDNAInputSchema},
  output: {schema: AnalyzeStyleDNAOutputSchema},
  prompt: `You are a personal stylist for discerning, fashion-forward clients who have a taste for middle to upper-class fashion, including designer and high-quality brands.
  These clients often appreciate designers known for sustainable luxury, modern tailoring, and timeless appeal, such as Gabriella Hearst, The Row, or Brunello Cucinelli, reflecting sophisticated tastes that resonate across Gen X, Y, and Z.
  Use British English terminology and spelling throughout your response (e.g., "trousers" instead of "pants", "jumper" instead of "sweater", "colour" instead of "color", "trainers" instead of "sneakers").
  Your summary should use contemporary fashion language that is sophisticated and appeals to Gen X, Y, and Z. For example, when referring to garments, prefer 'top' or 'shirt' over 'blouse' unless specifically referring to a traditional blouse.

  Analyze the following information to determine the user's style DNA. CRITICALLY, your analysis MUST be primarily based on the SPECIFIC items and brands listed in the 'Wardrobe Data' and 'Shoe Collection Data'.
  Infer their preferred styles, colours, and designers directly from these lists. Consider how their calendar events and weather might influence how they utilize these items.

  Wardrobe Data (User's actual clothing items): {{{wardrobeData}}}
  Shoe Collection Data (User's actual shoes): {{{shoeCollectionData}}}
  AccuWeather Information: Temperature: {{{accuWeatherInfo.temperature}}}°C, Condition: {{{accuWeatherInfo.condition}}}
  Google Calendar Events:
  {{#each googleCalendarEvents}}
  - Event: {{{eventName}}}, Starts: {{{eventStartDateTime}}}, Ends: {{{eventEndDateTime}}}, Type: {{{eventType}}}{{#if eventLocation}}, Location: {{{eventLocation}}}{{/if}}
  {{/each}}

  Based *primarily* on the user's specific wardrobe and shoe items, create a concise summary of their style DNA, aiming for approximately 3-4 lines of text. The summary should be easily readable and digestible at a glance.
  Focus on the types of clothing they own (e.g., "owns several designer silk tops and tailored trousers"), their go-to brands (e.g., "favours Chanel and Gucci"), common colour palettes evident in their collection (e.g., "a wardrobe rich in neutrals with accents of cream and beige"), and how their high-end shoe collection (e.g., "collection of designer heels like Manolo Blahnik pumps and Chanel slingbacks") complements these pieces.
  
  CRITICAL INSTRUCTION FOR 'styleDNA' FIELD:
  The value for the 'styleDNA' field in your output MUST be a single, concise, plain text summary paragraph, approximately 3-4 lines long.
  YOUR FINAL OUTPUT FOR THE 'styleDNA' FIELD MUST BE RAW, UNWRAPPED, UNESCAPED TEXT. DO NOT WRAP IT IN A JSON STRUCTURE.
  - It MUST use British English and contemporary fashion terms.
  - It MUST NOT be a JSON object.
  - It MUST NOT be a string representation of a JSON object.
  - It MUST NOT replicate any part of the input JSON structure.
  - It must ONLY be the descriptive paragraph text itself.
  For example, a correct value for 'styleDNA' would be: "Based on their collection of Burberry trench coats and Gucci silk tops, the user's style is characterized by a blend of classic British tailoring and Italian luxury. Their shoe collection, featuring Chanel slingbacks and Manolo Blahnik pumps, indicates a preference for sophisticated chic, often pairing these with neutral-toned Loro Piana cashmere for an elegant, understated look."
  Do NOT output something like: "{\\"styleDNA\\": \\"The user's style is...\\"}" or similar. If you absolutely cannot derive a meaningful styleDNA from the input, provide a generic but well-phrased British English style assessment like: "The client possesses a refined and fashion-conscious approach to their wardrobe, favouring high-quality pieces and designer labels that suggest an appreciation for sophisticated and timeless elegance. Their collection hints at a penchant for luxurious materials and classic silhouettes, often found in middle to upper-class fashion circles."
  `,
});

const analyzeStyleDNAFlow = ai.defineFlow(
  {
    name: 'analyzeStyleDNAFlow',
    inputSchema: AnalyzeStyleDNAInputSchema,
    outputSchema: AnalyzeStyleDNAOutputSchema,
  },
  async input => {
    const { output } = await prompt(input);

    // Default fallback text
    const fallbackOutput = { styleDNA: "The client possesses a refined and fashion-conscious approach to their wardrobe, favouring high-quality pieces and designer labels that suggest an appreciation for sophisticated and timeless elegance. Their collection hints at a penchant for luxurious materials and classic silhouettes, often found in middle to upper-class fashion circles." };

    // Initial check for a valid output object
    if (!output || typeof output.styleDNA !== 'string') {
        console.error("AI returned null or invalid type for styleDNA:", output);
        return fallbackOutput;
    }

    let styleDNAText = output.styleDNA.trim();

    // Enhanced Safeguard: Check if the AI returned a stringified JSON and attempt to parse it.
    if (styleDNAText.startsWith('{') && styleDNAText.endsWith('}')) {
        try {
            const parsed = JSON.parse(styleDNAText);
            // If parsing is successful and contains the nested field, extract it.
            if (parsed && typeof parsed.styleDNA === 'string' && parsed.styleDNA.trim()) {
                console.warn("Warning: AI returned a stringified JSON. Extracting nested 'styleDNA' value.");
                styleDNAText = parsed.styleDNA.trim();
            } else {
                // The string looked like JSON but didn't contain the data we need.
                console.error("Error: AI output was a JSON-like string but did not contain a valid nested 'styleDNA' field.", output);
                return fallbackOutput;
            }
        } catch (e) {
            // The string was not valid JSON, treat it as plain text but log a warning.
            console.warn("Warning: AI output starts and ends with braces but failed to parse as JSON. Treating as plain text.", e);
        }
    }

    // Final validation on the resulting text.
    if (styleDNAText.length < 20) {
        console.error("Error: Final styleDNA text is too short or empty after processing.", output);
        return fallbackOutput;
    }

    // Return the cleaned, valid output.
    return { styleDNA: styleDNAText };
  }
);
