// This is an autogenerated file from Firebase Studio.
// If you edit it, your changes may be overwritten.

"use client";

import { ReactNode, useEffect, useState } from "react";
// FIX: Changed relative path to alias path for correct bundling
import { FirebaseProvider } from "@/firebase/provider";

/**
 * A provider that ensures Firebase is initialized only on the client.
 *
 * This component is necessary to prevent Firebase from being initialized on
 * the server, which can cause issues with server-rendering.
 *
 * @see https://firebase.google.com/docs/web/troubleshooting#server-side-rendering
 */
export function FirebaseClientProvider({ children }: { children: ReactNode }) {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  return isClient ? <FirebaseProvider>{children}</FirebaseProvider> : null;
}