// This is an autogenerated file from Firebase Studio.
// If you edit it, your changes may be overwritten.

import type { FirebaseOptions } from "firebase/app";

/**
 * The configuration for the default Firebase app.
 *
 * This is read automatically by `initializeFirebase` and used to connect
 * to your Firebase project. You can find this information in your

 * Firebase project's web app settings.
 *
 * @see https://firebase.google.com/docs/web/setup#config-object
 */
export const firebaseConfig: FirebaseOptions = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};
