// This is an autogenerated file from Firebase Studio.
// If you edit it, your changes may be overwritten.

import {
  type FirebaseApp,
  getApps,
  initializeApp,
} from "firebase/app";
import { Auth, getAuth } from "firebase/auth";
import { Firestore, getFirestore } from "firebase/firestore";
import { firebaseConfig } from "./config";
import { getStorage, FirebaseStorage } from "firebase/storage";

let app: FirebaseApp | null = null;
let auth: Auth | null = null;
let firestore: Firestore | null = null;
let storage: FirebaseStorage | null = null;

/**
 * Initializes the default Firebase app, if it hasn't been initialized already.
 *
 * @returns An object containing the initialized Firebase App, Auth, and Firestore services.
 */
export function initializeFirebase(): {
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
  storage: FirebaseStorage;
} | null {

  if (!firebaseConfig.apiKey) {
    console.error("Firebase API key is missing. Please check your environment variables.");
    return null;
  }

  if (getApps().length === 0) {
    try {
      const newApp = initializeApp(firebaseConfig);
      app = newApp;
      auth = getAuth(newApp);
      firestore = getFirestore(newApp);
      storage = getStorage(newApp);
    } catch(e) {
        console.error("Firebase initialization failed:", e)
        return null;
    }
  } else {
    const existingApp = getApps()[0];
    app = existingApp;
    auth = getAuth(existingApp);
    firestore = getFirestore(existingApp);
    storage = getStorage(existingApp);
  }

  return { app, auth, firestore, storage };
}
