import { Timestamp } from 'firebase-admin/firestore';

// The allowed transaction categories for the ecosystem
export type TransactionType = 
  | 'EARN_HARDWARE_SYNC'  // Syncing a SkoBoxie
  | 'EARN_DAILY_LOGIN'    // Opening the digital closet
  | 'SPEND_RAG_QUERY'     // Generating an AI outfit
  | 'SPEND_MARKETPLACE'   // Buying hardware drops
  | 'ADMIN_ADJUSTMENT';

export interface TokenTransaction {
  id?: string;            // Auto-generated by Firestore
  amount: number;         // Positive to add tokens, negative to subtract
  type: TransactionType;
  description: string;    // Human-readable receipt (e.g., "AI Outfit Generation")
  timestamp: Timestamp;   // Server-side timestamp
  referenceId?: string;   // Optional: ID of the generated outfit or hardware ping
}

// Partial interface extending your existing User profile
export interface UserProfile {
  // ... your existing fields
  tokenBalance: number;
}